#Defines the maximum amount of docks that can be placed direction the world
# Default: 128
# Range: 0 ~ 10000
maxDockAmount = 128
#Defines how many packages santa can extract/deliver when passing by a dock
# Default: 4
# Range: > 0
maxPackagesPerDelivery = 4
#Defines at what percentage of charge an elf starts looking for potential charge stations
# Default: 50
# Range: 0 ~ 100
elfRechargePercentage = 50
#Defines how many ticks it takes for an elf to lower his stress by 1
# Default: 400
# Range: > 0
elfUnstressCooldown = 400
#How much trust is required to be able to give santa all type A items
# Default: 1000
# Range: > 0
typeATrust = 1000
#How much trust is required to be able to give santa all type A items
# Default: 10000
# Range: > 0
typeBTrust = 10000
