# Don't change this! Version used to track needed updates.
version = 2

[disabler]
disabledEnchantmentsV2 = [
    [ "minecraft:breach", { table = false, loot = false, trade = false } ],
    [ "minecraft:protection", { table = false, loot = false, trade = false } ],
    [ "minecraft:cleaving", { table = false, loot = false, trade = false } ],
    [ "minecraft:power", { table = false, loot = false, trade = false } ],
    [ "minecraft:sharpness", { table = false, loot = false, trade = false } ],
    [ "enchantencore:sonic", { table = false, loot = false, trade = false } ],
    [ "enchantencore:regrowth", { table = false, loot = false, trade = false } ],
    
    [ "soulbound:soulbound", { table = false, loot = true, trade = true } ],
    [ "minecraft:mending", { table = false, loot = true, trade = true } ],
    
    [ "minecraft:unbreaking", { table = true, loot = true, trade = true } ],
    [ "minecraft:looting", { table = true, loot = true, trade = true } ],
    [ "minecraft:fortune", { table = true, loot = true, trade = true } ],
    [ "minecraft:efficiency", { table = true, loot = true, trade = true } ],
    [ "minecraft:silktouch", { table = true, loot = true, trade = true } ],

    [ "minecraft:vanishing_curse", { table = true, loot = true, trade = false } ],
    [ "minecraft:binding_curse", { table = true, loot = true, trade = false } ],
    [ "minecraft:wind_burst", { table = true, loot = true, trade = false } ],
    [ "enchantencore:ownership_curse", { table = true, loot = true, trade = false } ],
    [ "enchantencore:caravan_curse", { table = true, loot = true, trade = false } ],
    [ "enchantencore:ownership_curse", { table = true, loot = true, trade = false } ],
    [ "enchantencore:caravan_curse", { table = true, loot = true, trade = false } ],  
    [ "enchantencore:hiding_curse", { table = true, loot = true, trade = false } ],   
    [ "enchantencore:reach_curse", { table = true, loot = true, trade = false } ],   
    [ "enchantencore:fragility_curse", { table = true, loot = true, trade = false } ],   
    [ "enchantencore:welfare_curse", { table = true, loot = true, trade = false } ],   
    [ "enchantencore:randomness_curse", { table = true, loot = true, trade = false } ],   
    [ "enchantencore:death_curse", { table = true, loot = true, trade = false } ],    
    [ "enchantencore:breeze_curse", { table = true, loot = true, trade = false } ], 
    [ "enchantencore:crank_curse", { table = true, loot = true, trade = false } ],  
    [ "enchantencore:crab_claw", { table = true, loot = true, trade = false } ],    
    [ "enchantencore:haste", { table = true, loot = true, trade = false } ],    
    [ "enchantencore:gluttony", { table = true, loot = true, trade = false } ],    

]
disabledEnchantments = [  ]

[maxLevel]
maxLevels = [  ]
globalMaxLevel = 0
limitObtainableEnchantmentLevel = false
obtainableEnchantmentLevels = [  ]

[trades]
limitBookTradeLevel = false
bookTradeLevelLimit = 5
modifyEnchantedBookTradeUses = false
maxEnchantedBookTradeUses = 12
modifyEnchantedItemTradeUses = false
maxEnchantedItemTradeUses = 3
enchantedBookTradeRestockEnabled = true
enchantedItemTradeRestockEnabled = true

[enchantingTable]
enchantingTableEnabled = true
modifyMaxTablePower = false
maxTablePower = 15
modifyLapisCost = false
lapisCostFormula = "i+1"
modifyXpCost = false
xpCostFormula = "i+1"

[loot]
modifyEnchantWithLevelsMaxPower = false
enchantWithLevelsMaxPower = 50